apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page'),
    path('about/', views.AboutPageView.as_view(), name='about_page'),
    path('contact/', views.ContactPageView.as_view(), name='contact_page'),
    path('trainer/', views.TrainerPageView.as_view(), name='trainer_page'),

    path('login/', views.LoginPage.as_view(), name='login'),

    path('profile/', views.AdminProfilePageView.as_view(), name='profile'),

    path('instructor/create/', views.InstructorCreateView.as_view(),
        name='instructor_create'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.main.urls', namespace='main')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models.py
from django.db import models


class Instructor(models.Model):
    name = models.CharField(max_length=50)
    base = models.TextField()
    avatar = models.ImageField('Фото', upload_to='images/instructors')

    class Meta:
        verbose_name = 'Инструктор'
        verbose_name_plural = 'Инструктора'
        db_table = 'instructor'

    def __str__(self) -> str:
        return self.name
         

apps/main/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import Instructor


class InstructorForm(forms.ModelForm):

    class Meta:
        model = Instructor
        fields = '__all__'

apps/main/views.py
from django.urls import reverse
from django.views.generic import TemplateView, CreateView
from .forms import InstructorForm
from .models import Instructor

class HomePageView(TemplateView):
    template_name ='base.html'


class AboutPageView(TemplateView):
    template_name = 'about/index.html'


class ContactPageView(TemplateView):
    template_name = 'contact/index.html'


class TrainerPageView(TemplateView):
    template_name = 'trainers/index.html'


class LoginPage(TemplateView):
    template_name = 'auth/login.html'


class AdminProfilePageView(TemplateView):
    template_name = 'admin/index.html'


class InstructorCreateView(CreateView):
    form_class = InstructorForm
    model = Instructor
    template_name = 'create/instructor/create_instructor.html'

    def get_success_url(self) -> str:
        return reverse('main:instructor_create')

templates/about/blog_section.html
{% load static %}
<section class="about-blog-section spad">
    <div class="container">
        <div class="section-title text-center">
            <img src="{% static 'img/icons/logo-icon.png' %}" alt="">
            <h2>Course benefits</h2>
            <p>Practice Yoga to perfect physical beauty, take care of your soul and enjoy life more fully!</p>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="blog-item">
                    <img src="{% static 'img/blog/1.jpg' %}" alt="">
                    <div class="bi-text">
                        <h2><a href="single-blog.html">Yoga for Slim Physique</a></h2>
                        <p>Regular practice with breathing tech-niques in Yoga will help you get a toned body, this is the perfect choice</p>
                    </div>
                    <div class="bi-footer">
                        <div class="bi-cata">Health & Beauty</div>
                        <div class="bi-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/about/header_section.html
{% load static %}
<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 m-auto text-white">
                <h2>О нас</h2>
                <p>assssssssdasdasdasdasdasd</p>
            </div>
        </div>
    </div>
</section>

templates/about/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	<title>О нас</title>
{% endblock %}

{% block body %}
	
	{% include 'about/header_section.html' %}

	{% include 'about/service_section.html' %}

	{% include 'about/what_we_do.html' %}

	{% include 'about/trainer_section.html'%}

	{% include 'about/review_section.html' %}

	{% include 'about/blog_section.html' %}

{% endblock %}

</html>

templates/about/review_section.html
{% load static %}
<section class="review-section spad set-bg" data-setbg="{% static 'img/review-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 m-auto">
                <div class="review-slider owl-carousel">
                    <div class="review-item">
                        <div class="ri-img">
                            <img src="{% static 'img/classes/author/1.jpg' %}" alt="">
                        </div>
                        <div class="ri-text text-white">
                            <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness.</p>
                            <h4>Denise Thomas</h4>
                            <h6>Designer</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/about/service_section.html
{% load static %}
<section class="service-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="about-item icon-box">
                    <div class="ai-icon">
                        <img src="{% static 'img/icons/about-1.png' %}" alt="">
                    </div>
                    <div class="ai-text">
                        <h4>Full Rejuvenation</h4>
                        <p>Excepteur sint occaecat cupidatat non proident sunt</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="about-item icon-box">
                    <div class="ai-icon">
                        <img src="{% static 'img/icons/about-2.png' %}" alt="">
                    </div>
                    <div class="ai-text">
                        <h4>Extension of Spring</h4>
                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="about-item icon-box">
                    <div class="ai-icon">
                        <img src="{% static 'img/icons/about-3.png' %}" alt="">
                    </div>
                    <div class="ai-text">
                        <h4>Against Aging</h4>
                        <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="about-item icon-box">
                    <div class="ai-icon">
                        <img src="{% static 'img/icons/about-4.png' %}  " alt="">
                    </div>
                    <div class="ai-text">
                        <h4>Slim Body</h4>
                        <p>Neque porro quisquam est, qui dolorem ipsum quia dolor</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/about/trainer_section.html
{% load static %}
<section class="trainer-section overflow-hidden spad">
    <div class="container">
        <div class="section-title text-center">
            <img src="img/icons/logo-icon.png" alt="">
            <h2>Our Trainer Yoga</h2>
            <p>Practice Yoga to perfect physical beauty, take care of your soul and enjoy life more fully!</p>
        </div>
        <div class="trainer-slider owl-carousel">
            <div class="ts-item">
                <div class="trainer-item">
                    <div class="ti-img">
                        <img src="{% static 'img/trainer/1.png' %}" alt="">
                    </div>
                    <div class="ti-text">
                        <h4>Lori Kennedy</h4>
                        <h6>Yoga Trainer</h6>
                        <p>Yoga & Therapy Certificate of Uttarakhand University Sanskrit</p>
                        <div class="ti-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/about/what_we_do.html
{% load static %}
<section class="wwd-section spad set-bg" data-setbg="{% static 'img/wwd-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-7 ml-auto">
                <div class="wwd-text">
                    <h3>What we do</h3>
                    <p>To be invited to the nearest Cali center and get free physical advice to learn more about the program.</p>
                    <div class="single-progress-item">
                        <p>Breathing</p>
                        <div class="progress-bar-style" data-progress="84"  data-bgcolor="#f76d63"></div>
                    </div>
                    <div class="single-progress-item">
                        <p>Metabolism</p>
                        <div class="progress-bar-style" data-progress="75"  data-bgcolor="#f76d63"></div>
                    </div>
                    <div class="single-progress-item">
                        <p>Flexibility</p>
                        <div class="progress-bar-style" data-progress="90"  data-bgcolor="#f76d63"></div>
                    </div>
                    <div class="single-progress-item">
                        <p>Strongness</p>
                        <div class="progress-bar-style" data-progress="78"  data-bgcolor="#f76d63"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}
		<title>Yoga Orzu</title>
	{% endblock %}
	
	{% include 'includes/head.html' %}
</head>

<body>
	<div id="preloder">
		<div class="loader"></div>
	</div>
	{% block header %}
	{% include 'includes/header.html'%}
	{% endblock header %}
	

	{% block body %}

	<!-- Hero Section -->
	<section class="hero-section">
		<div class="arrow-buttom">
			<img src="{% static 'img/icons/arrows-buttom.png' %}" alt="">
		</div>
		<div class="hero-slider owl-carousel">
			<div class="hs-item">
				<div class="hs-style-1 text-center">
					<img src="{% static 'img/hero-slider/1.png' %}" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- Hero Section end -->

	<!-- About Section -->
	<section class="about-section spad">
		<div class="container">
			<div class="section-title text-center">
				<img src="{% static 'img/icons/logo-icon.png' %}" alt="">
				<h2>Welcome to Ahana</h2>
				<p>Practice Yoga to perfect physical beauty, take care of your soul and enjoy life more fully!</p>
			</div>
			<div class="row">
				<div class="col-lg-6">
					<div class="about-img">
						<img src="{% static 'img/about.png' %}" alt="">
					</div>
				</div>
				<div class="col-lg-6">
					<div class="about-item">
						<div class="ai-icon">
							<img src="{% static 'img/icons/about-1.png' %}" alt="">
						</div>
						<div class="ai-text">
							<h4>Full Rejuvenation</h4>
							<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
						</div>
					</div>
					<div class="about-item">
						<div class="ai-icon">
							<img src="{% static 'img/icons/about-2.png' %}" alt="">
						</div>
						<div class="ai-text">
							<h4>Extension of Spring</h4>
							<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem a cusantium doloremque.</p>
						</div>
					</div>
					<div class="about-item">
						<div class="ai-icon">
							<img src="{% static 'img/icons/about-3.png' %}" alt="">
						</div>
						<div class="ai-text">
							<h4>Against Aging</h4>
							<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
						</div>
					</div>
					<a href="" class="site-btn sb-gradient mt-5">explore more</a>
				</div>
			</div>
		</div>
	</section>
	<!-- About Section end -->

	<!-- Classes Section -->
	<section class="classes-section spad">
		<div class="container">
			<div class="section-title text-center">
				<img src="{% static 'img/icons/logo-icon.png' %}" alt="">
				<h2>Popular Classes виды</h2>
				<p>Practice Yoga to perfect physical beauty, take care of your soul and enjoy life more fully!</p>
			</div>
			<div class="classes-slider owl-carousel">
				<div class="classes-item">
					<div class="ci-img">
						<img src="{% static 'img/classes/2.jpg' %}" alt="">
					</div>
					<div class="ci-text">
						<h4>Traditional Hatha</h4>
						<div class="ci-metas">
							<div class="ci-meta"><i class="material-icons">event_available</i>Mon, Wed, Fri</div>
							<div class="ci-meta"><i class="material-icons">alarm_on</i>06:30pm - 07:45pm</div>
						</div>
						<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis</p>
					</div>
					<div class="ci-bottom">
						<div class="ci-author">
							<img src="{% static 'img/classes/author/2.jpg' %}" alt="">
							<div class="author-text">
								<h6>Victoria Webb</h6>
								<p>Yoga Trainer</p>
							</div>
						</div>
						<a href="" class="site-btn sb-gradient">book now</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Classes Section end -->

	<!-- Trainer Section -->
	<section class="trainer-section overflow-hidden spad">
		<div class="container">
			<div class="section-title text-center">
				<img src="{% static 'img/icons/logo-icon.png' %}" alt="">
				<h2>Our Trainer Yoga</h2>
				<p>Practice Yoga to perfect physical beauty, take care of your soul and enjoy life more fully!</p>
			</div>
			<div class="trainer-slider owl-carousel">
				<div class="ts-item">
					<div class="trainer-item">
						<div class="ti-img">
							<img src="{% static 'img/trainer/1.png' %}" alt="">
						</div>
						<div class="ti-text">
							<h4>Lori Kennedy</h4>
							<h6>Yoga Trainer</h6>
							<p>Yoga & Therapy Certificate of Uttarakhand University Sanskrit</p>
							<div class="ti-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-instagram"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!-- Trainer Section end -->

	<!-- Event Section -->
	<section class="event-section spad">
		<div class="container">
			<div class="section-title text-center">
				<img src="{% static 'img/icons/logo-icon.png' %}" alt="">
				<h2>Upcoming Events</h2>
				<p>Practice Yoga to perfect physical beauty, take care of your soul and enjoy life more fully!</p>
			</div>
			<div class="row">
				<div class="col-xl-6">
					<div class="event-video">
						<img src="{% static 'img/video.jpg' %}" alt="">
						<a href="https://www.youtube.com/watch?v=vgv-hzTl5FA" class="video-popup"><img src="img/icons/play.png" alt=""></a>
					</div>
				</div>
				<div class="col-xl-6">
					<div class="event-item">
						<div class="ei-img">
							<img src="{% static 'img/event/1.jpg' %}" alt="">
						</div>
						<div class="ei-text">
							<h4><a href="#">Lole White Yoga Tour</a></h4>
							<ul>
								<li><i class="material-icons">person</i>Kelly Alexander</li>
								<li><i class="material-icons">event_available</i>15 January, 2019</li>
								<li><i class="material-icons">map</i>184 Main Collins Street</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Event Section end -->

	<!-- Sign up Section -->
	<section class="signup-section spad">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="signup-map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d33245.297803635964!2d-73.76987401620775!3d40.704774398815005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sbd!4v1575866843291!5m2!1sen!2sbd" style="border:0;" allowfullscreen=""></iframe></div>
				</div>
				<div class="col-lg-6">
					<div class="singup-text">
						<h3>Sign Up for Our Classes</h3>
						<p>To be invited to the nearest Cali center and get free physical advice to learn more about the program.</p>
					</div>
					<form class="singup-form">
						<div class="row">
							<div class="col-md-6">
								<input type="text" placeholder="First Name">
							</div>
							<div class="col-md-6">
								<input type="text" placeholder="Last Name">
							</div>
							<div class="col-md-6">
								<input type="text" placeholder="Your Email">
							</div>
							<div class="col-md-6">
								<input type="text" placeholder="Phone Number">
							</div>
							<div class="col-md-12">
								<textarea placeholder="Message"></textarea>
								<a href="#" class="site-btn sb-gradient">Get started</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	{% endblock %}

	{% include 'includes/footer.html' %}

	{% block srcipts %}
		{% include 'includes/scripts.html' %}
	{% endblock %}
	
</body>

</html>

templates/contact/form.html
<form class="singup-form contact-form">
    <div class="row">
        <div class="col-md-6">
            <input type="text" placeholder="First Name">
        </div>
        <div class="col-md-6">
            <input type="text" placeholder="Last Name">
        </div>
        <div class="col-md-6">
            <input type="text" placeholder="Your Email">
        </div>
        <div class="col-md-6">
            <input type="text" placeholder="Phone Number">
        </div>
        <div class="col-md-12">
            <textarea placeholder="Message"></textarea>
            <a href="#" class="site-btn sb-gradient">Send message</a>
        </div>
    </div>
</form>

templates/contact/header_section.html
{% load static %}
<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 m-auto text-white">
                <h2>Contact</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>
    </div>
</section>

templates/contact/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	<title>Контакты</title>
{% endblock %}
	

{% block body %}
    
{% include 'contact/header_section.html' %}

	<section class="contact-page-section spad overflow-hidden">
		<div class="container">
			<div class="contact-map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d33245.297803635964!2d-73.76987401620775!3d40.704774398815005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sbd!4v1575866843291!5m2!1sen!2sbd" style="border:0;" allowfullscreen=""></iframe></div>
			<div class="row">
				<div class="col-lg-4">
					<div class="con-info">
						<h3>Visit the Yoga Ahana</h3>
						<ul>
							<li><i class="material-icons">map</i>184 Main Collins Street</li>
						</ul>
					</div>
					<div class="con-info">
						<h3>Message Us</h3>
						<ul>
							<li><i class="material-icons">map</i>(965) 436 3274</li>
							<li><i class="material-icons">map</i>ahana.yoga@gmail.com</li>
						</ul>
					</div>
					<div class="con-info">
						<h3>Opening Hours</h3>
						<ul>
							<li><i class="material-icons">map</i>Mon - Fri:  6:30am - 07:45pm</li>
							<li><i class="material-icons">map</i>Sat - Sun:  8:30am - 05:45pm</li>
						</ul>
					</div>
					<div class="contact-social">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-instagram"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
					</div>
				</div>
				<div class="col-lg-8">
					{% include 'contact/form.html' %}
				</div>
			</div>
		</div>
	</section>

    {% endblock %}

</html>

templates/create/instructor/create_instructor.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'create/instructor/header_section.html' %}

{% endblock %}
<br/><br/>
{% block body %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>@fat</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td colspan="2">Larry the Bird</td>
        <td>@twitter</td>
      </tr>
    </tbody>
  </table>
{% endblock body %}

templates/create/instructor/header_section.html
{% load static %}
<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 m-auto text-white">
                <h2>Инструктор</h2>
                <p>Тут вы можете редактировать инструктора</p>
            </div>
        </div>
    </div>
</section>

templates/includes/footer.html
{% load static %}
<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget">
                    <div class="about-widget">
                        <img src="{% static 'img/logo-3.png' %}" alt="">
                        <p>Lorem ipsum dolor sit amet, consec-tetur adipiscing elit sed.</p>
                        <ul>
                            <li><i class="material-icons">phone</i>(965) 436 3274</li>
                            <li><i class="material-icons">email</i>ahana.yoga@gmail.com</li>
                            <li><i class="material-icons">map</i>184 Main Collins Street</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget pl-0 pl-lg-5">
                    <h2 class="fw-title">Company</h2>
                    <ul>
                        <li><a href="#">Online Education</a></li>
                        <li><a href="#">Gallery</a></li>
                        <li><a href="#">Special Issues</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-sm-6">
                <div class="footer-widget">
                    <h2 class="fw-title">About Us</h2>
                    <ul>
                        <li><a href="#">Our Vision</a></li>
                        <li><a href="#">Our Mission</a></li>
                        <li><a href="#">Meet The Team</a></li>
                        <li><a href="#">Introduce</a></li>
                        <li><a href="#">Customer Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="footer-widget pl-0 pl-lg-5">
                    <h2 class="fw-title">Open time</h2>
                    <ul>
                        <li><i class="material-icons">alarm_on</i>Mon - Fri:  6:30am - 07:45pm</li>
                        <li><i class="material-icons">alarm_on</i>Sat - Sun:  8:30am - 05:45pm</li>
                    </ul>
                    <form class="infor-form">
                        <input type="text" placeholder="Your Email">
                        <button><img src="{% static 'img/icons/send.png' %}" alt=""></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="row">
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="description" content="Ahana Yoga HTML Template">
<meta name="keywords" content="yoga, html">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %} "/>
<link rel="stylesheet" href="{% static 'css/nice-select.css' %}"/>
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

templates/includes/header.html
{% load static %}
<header class="header-section">
    <div class="header-bottom">
        <a href="index.html" class="site-logo">
            <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <div class="container">
            <ul class="main-menu">
                <li><a href="{% url 'main:home_page' %}" class="active">Главная</a></li>
                <li><a href="{% url 'main:about_page' %}">О нас</a></li>
                <li><a href="{% url 'main:trainer_page' %}">Инструктор</a></li>
                <li><a href="{% url 'main:contact_page' %}">Контакты</a></li>
                {% if user.is_authenticated %}
                    <li><a href="#">Админ</a>
                        <ul class="sub-menu">
                            <li><a href="{% url 'main:profile' %}">Профиль</a></li>
                            <li><a href="{% url 'logout' %}">Выход</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>

templates/includes/scripts.html
{% load static %}
<script src="{% static 'js/vendor/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/trainers/header_section.html
{% load static %}
<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 m-auto text-white">
                <h2>Инструктора</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
        </div>
    </div>
</section>

templates/trainers/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Тренер</title>
{% endblock %}

{% block body %}

{% include 'trainers/header_section.html' %}

{% include 'trainers/trainers_section.html' %}

{% endblock %}

templates/trainers/trainers_section.html
{% load static %}
<section class="trainers-page-section spad overflow-hidden">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="trainer-item">
                    <div class="ti-img">
                        <img src="{% static 'img/trainer/q.png' %}" alt="">
                    </div>
                    <div class="ti-text">
                        <h4>Атаджанов Рустам Фархадович</h4>
                        <h6>Йога Инструктор</h6>
                        <p>Yoga & Therapy Certificate of Uttarakhand University Sanskrit</p>
                        <div class="ti-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="site-pagination">
            <a href="#" class="active">1</a>
            <a href="#">2</a>
            <a href="#"><i class="material-icons">keyboard_arrow_right</i></a>
        </div>
    </div>
</section>